# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mezuro
email: mezurometrics@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Mezuro project attempts to provide a platform
  to compare projects and metric techniques,
  teaching how to use metrics through configurations
  and code analysis, avoid technical debts and
  disseminate code metrics usage and understanding.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mezuro.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: mezuro
# google_play: 'GDGX'
# google_plus_com: '109485346959707049693'  # Community link
# google_plus_per: '+GDGManagua'  #Personal link
# facebook_app_id: 12345

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

# more_vert:
#   option1:
#     name: Cool Option 1
#     link: www.myawesomelink.com
#   option2:
#     name: Cool Option 2
#     link: www.myawesomelink.com
#   option3:
#     name: Cool Option 3
#     link: www.myawesomelink.com

disqus: false
# disqus_shortname: 'gdgmanagua'

# Build settings
markdown: kramdown
